version: "3.3"  # optional since v1.27.0
services:
  mycovidapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - covid_db
  covid_db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-covid-data:/var/lib/postgresql/data

volumes:
  postgres-covid-data: