// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/country/cases": {
            "get": {
                "description": "Gets a list of Cases for Malaysia",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "List Cases for Country",
                "parameters": [
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD. If omitted, will return data from start of records",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD. If omitted, will return data to end of records",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Cases"
                            }
                        }
                    },
                    "422": {
                        "description": "Invalid parameters passed",
                        "schema": {
                            "$ref": "#/definitions/server.ValidationError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Cases": {
            "type": "object",
            "properties": {
                "activeCases": {
                    "type": "integer"
                },
                "clusterCases": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "fullyVaxCases": {
                    "type": "integer"
                },
                "importCases": {
                    "type": "integer"
                },
                "newCases": {
                    "type": "integer"
                },
                "nonVaxCases": {
                    "type": "integer"
                },
                "partialVaxCases": {
                    "type": "integer"
                },
                "recovered": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "server.ValidationError": {
            "type": "object",
            "properties": {
                "loc": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "MYCovidAPI",
	Description: "RESTful API for Covid dataset provided by Ministry of Health Malaysia",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
