definitions:
  models.Cases:
    properties:
      activeCases:
        type: integer
      clusterCases:
        type: integer
      date:
        type: string
      fullyVaxCases:
        type: integer
      importCases:
        type: integer
      newCases:
        type: integer
      nonVaxCases:
        type: integer
      partialVaxCases:
        type: integer
      recovered:
        type: integer
      state:
        type: string
      updatedAt:
        type: string
    type: object
  server.ValidationError:
    properties:
      loc:
        type: string
      msg:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
  description: RESTful API for Covid dataset provided by Ministry of Health Malaysia
  title: MYCovidAPI
  version: "1.0"
paths:
  /country/cases:
    get:
      description: Gets a list of Cases for Malaysia
      parameters:
      - description: YYYY-MM-DD. If omitted, will return data from start of records
        in: query
        name: start_date
        type: string
      - description: YYYY-MM-DD. If omitted, will return data to end of records
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Cases'
            type: array
        "422":
          description: Invalid parameters passed
          schema:
            $ref: '#/definitions/server.ValidationError'
      summary: List Cases for Country
      tags:
      - cases
swagger: "2.0"
